// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1u8r65icfA8Gsge0gRG2r4JJ-KOd2WY',
    appId: '1:371794930649:web:b511c8060980f1768147c8',
    messagingSenderId: '371794930649',
    projectId: 'marc-x-andre',
    authDomain: 'marc-x-andre.firebaseapp.com',
    databaseURL: 'https://marc-x-andre-default-rtdb.firebaseio.com',
    storageBucket: 'marc-x-andre.appspot.com',
    measurementId: 'G-F2LH16MFV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmLB8Pgo4TtezC4Wu8UaXOia2yREaeTKM',
    appId: '1:371794930649:android:89e64aab575d17848147c8',
    messagingSenderId: '371794930649',
    projectId: 'marc-x-andre',
    databaseURL: 'https://marc-x-andre-default-rtdb.firebaseio.com',
    storageBucket: 'marc-x-andre.appspot.com',
  );
}
